### PR TITLE
Update to version 2.4.1 of MFizz.

### LINKED ISSUE #1: Docker icon
The docker icon is missing. Could you point me to some instructions on how to add it? PR will follow.

### PR DESCRIPTION
**Pull request by kdungs**
Also introduce a small Python script to automatically generate the .sty
file from the .css file inside the [font-mfizz
repository](https://github.com/fizzed/font-mfizz).

This should fix #1.

In the long run, the .ttf file should also be taken from the submodule.

A CTAN release of this updated version is on the way.

### CODE REVIEW

**Comment by betatim** [comment]
Is there a dummy's guide somewhere which commands I should type? You might know very little about CTAN, but I know zero ;)

**Comment by kdungs** [comment]
Yeah, agreed. Ideally there should be a README for the repo that explains how to generate everything. How do you feel about having a release branch which contains exactly what's available through CTAN i.e.
 * README
 * LICENSE
 * font-mfizz.ttf
 * fontmfizz.sty
 * fontmfizz.tex
 * fontmfizz.pdf

and have master only contain the stuff that's necessary to generate those files including instructions on how to build them?

**Comment by betatim** [comment]
Why store the release stuff in the repo at all? Maybe keep the PDF for preview purposes.

 👍 for a README.

**Comment by mbr** [comment]
This may be dead, but I just spent 15 minutes implementing roughly the same thing. Should I open a PR? Seems like this just needs to be merged instead =).

**Comment by betatim** [comment]
If you can revive @kdungs' GitHub life I will buy you a drink!

**Comment by kdungs** [comment]
Hi folks,

I looked into this. I submitted an update to CTAN on 2017-03-19. Since then, mfizz hasn't changed. That's good :) 

Regarding this specific PR: In this repo, there is a branch that supports automated generation of the latex package from the font-mfizz repo. It would be nice if the actual package, i.e. what can be obtained from CTAN, would be available via this repo. Basically, I see two options, please let me know which one you prefer.

 1. Have `master` always contain the latest version of the package and tooling in a dedicated branch (basically as it is now - except I need to update `master` :) ).
2. Have the tools in `master` and offer downloads via releases.

Cheers,
Kevin

P.S. Tim, I think you owe Marc a beer now :P

**Comment by mbr** [comment]
@betatim Incidentally, I am not that far from Zurich =)

> Regarding this specific PR: In this repo, there is a branch that supports automated generation of the latex package from the font-mfizz repo. It would be nice if the actual package, i.e. what can be obtained from CTAN, would be available via this repo. Basically, I see two options, please let me know which one you prefer.

Not my decision, but I can see some merit in doing it incrementally, i.e. manually copying things into the repo so the script can find it would have solved my problems in 2 instead of 15 minutes, further automation is just the cherry on top!

**Comment by betatim** [comment]
> @betatim Incidentally, I am not that far from Zurich =)

If you ever come to visit Zurich or Basel let me know :)

**Comment by kdungs** [comment]
Just for closure on this one: It seems that there's no longer active development on the font itself. Therefore, we shouldn't bother with any more thoughts on automation. For now, there's the `automation` branch in case of any updates to mfizz in the future.

**Pull request closed without merging**
